### ISSUE TITLE
Faker throws runtime exception when faked type has method that returns an array

### ISSUE THREAD

**Issue by npryce** [dmcg/fakir#1]
Trying to fake javax.servlet.HttpServletRequest and call getCookies()

    HttpServletRequest request = Faker.fakeA(HttpServletRequest.class);
    request.getCookies();

throws: 
    java.lang.IllegalArgumentException: Cannot subclass final class class [Ljavax.servlet.http.Cookie;

**Comment by dmcg** [comment]
Fixed in 1.0.9

**Comment by npryce** [comment]
Yup that works.  Thanks.

**Comment by dmcg** [comment]
Just too late for your use-case!

**Comment by npryce** [comment]
I snuck in an upgrade just in time.
