### ISSUE TITLE
Cannot fake List<Something>

### ISSUE THREAD

**Issue by npryce** [dmcg/fakir#4]
`new Faker<List<Something>>(){}.get()` fails with a class cast exception:

```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
    at com.oneeyedmen.fakir.Faker.<init>(Faker.java:38)
    at com.oneeyedmen.fakir.Faker.<init>(Faker.java:42)
```

**Comment by dmcg** [comment]
As a workaround you could always go straight to 
`new FakeList(Something.class, 5, DefaultFactory.INSTANCE);`

**Comment by dmcg** [comment]
While the use-case for Fakir doesn't extend to lists, this is a problem for domain objects that are themselves generic.

**Comment by dmcg** [comment]
But that is a huge can of worms, as the types of fields can then depend on the generic signature.

**Comment by dmcg** [comment]
Now throws an UnsupportedOperationException when you try to
